### ISSUE TITLE
toDo ö

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [covid19br/nowcasting#7]
- [x] ajeitar a estrutura de pastas de output: /plots, /output_nowcasting, /tabelas_nowcasting_para_codigos (falta incluir /output_nowcasting como subpasta) ver README
- [x] incluir um parametro plot TRUE/FALSE para rodar com argumentos iguais
- [x] verificar a criação de plots 
- [x] corrigir o filtro de datas 15/03 para srag, botar condicional 
- [x] ajeitar a parte onde git faz push para outputDir
- [x] corrigir filtro de residentes/não residentes no município (está filtrando para residentes no caso de São Paulo)
- [x] verificar o código para as diferentes escalas e parâmetros asociados (sigla, DRS etc.)
- [x] ajustar a parametrização de campinas (window, trim) - isto é lá no repo deles
- [x] pensar um formato de relatório
- [x] implementar filtro de hospitalizados
- [ ] usar project root em todas os sources internos (mas não nos paths fornecidos na linha de comando)
- [ ] implementar filtro de residentes para estados? é a única escala que não usa isso

**Comment by saramortara** [comment]
não entendi o item: "corrigir filtro de residentes/não residentes no município". A ideia é deixar isso opcional? filtrar por residentes na localidade ou notificados na localidade?

**Comment by renatocoutinho** [comment]
Eu entendi que é isso, Sara, pra análises que vão na linha da projeção de leitos você precisa filtrar por localidade de notificação mesmo. Acho que Diogo até já fez alguma modificação pra poder reutilizar o código?

**Comment by AndreaSanchezTapia** [comment]
As análises não deveriam forçar esse filtro (como está para São Paulo) para cidades menores, deveria ser opcional. Mais um parâmetro, residentes true-false? 
Além do fato de que leitos usa outro filtro.

**Comment by renatocoutinho** [comment]
você precisa definir de algum jeito o que é caso do município ou não, então tem que filtrar ou por residente ou por notificação mesmo. Mais um parâmetro....

**Comment by AndreaSanchezTapia** [comment]
já tinha o parametro em read.sivep, só botei no parseOpts

**Comment by renatocoutinho** [comment]
hummm verdade, mas o read.sivep só aplica esse filtro se escala == municipio

**Comment by AndreaSanchezTapia** [comment]
Ainda não chequei nada de escala, incluindo os caminhos na outra issue. Mas você fechou ela, depois vejo o que falta.

**Comment by renatocoutinho** [comment]
A outra issue era outra coisa, mas a read.sivep já corrigi.

**Comment by renatocoutinho** [comment]
Filtro de hospitalizados está sendo feito numa etapa posterior, em `gera.nowcasting`, e o encaminhamento da solução de project root está indo via pacote ou por concatenação das funções, o que deixa só o último item por fazer, vou abrir issue específico e fechar este TO DO finalmente!
